

module.exports =
    t01:
        fontFamily:"HelveticaNeueW01-45Ligh,HelveticaNeueW02-45Ligh,HelveticaNeueW10-45Ligh,sans-serif"
        fontSize:"16px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t02:
        fontFamily:"HelveticaNeueW01-45Ligh,HelveticaNeueW02-45Ligh,HelveticaNeueW10-45Ligh,sans-serif"
        fontSize:"14px"
        color:"#162D3D"
        lineHeight:"18px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t03:
        fontFamily:"HelveticaNeueW01-55Roman,HelveticaNeueW02-55Roman,HelveticaNeueW10-55Roman,sans-serif"
        fontSize:"18px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t04:
        fontFamily:"HelveticaNeueW01-55Roman,HelveticaNeueW02-55Roman,HelveticaNeueW10-55Roman,sans-serif"
        fontSize:"12px"
        color:"#162D3D"
        lineHeight:"18px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t05:
        fontFamily:"HelveticaNeueW01-45Ligh,HelveticaNeueW02-45Ligh,HelveticaNeueW10-45Ligh,sans-serif"
        fontSize:"16px"
        color:"#162D3D"
        lineHeight:"18px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t06:
        fontFamily:"HelveticaNeueW01-55Roman,HelveticaNeueW02-55Roman,HelveticaNeueW10-55Roman,sans-serif"
        fontSize:"16px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t07:
        fontFamily:"HelveticaNeueW01-55Roman,HelveticaNeueW02-55Roman,HelveticaNeueW10-55Roman,sans-serif"
        fontSize:"14px"
        color:"#162D3D"
        lineHeight:"18px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t08:
        fontFamily:"HelveticaNeueW01-55Roman,HelveticaNeueW02-55Roman,HelveticaNeueW10-55Roman,sans-serif"
        fontSize:"20px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t09:
        fontFamily:"HelveticaNeueW01-65Romann,HelveticaNeueW02-65Romann,HelveticaNeueW10-65Romann,sans-serif"
        fontSize:"18px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t10:
        fontFamily:"HelveticaNeueW01-45Ligh,HelveticaNeueW02-45Ligh,HelveticaNeueW10-45Ligh,sans-serif"
        fontSize:"13px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t11:
        fontFamily:"HelveticaNeueW01-45Ligh,HelveticaNeueW02-45Ligh,HelveticaNeueW10-45Ligh,sans-serif"
        fontSize:"18px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t12:
        fontFamily:"HelveticaNeueW01-45Ligh,HelveticaNeueW02-45Ligh,HelveticaNeueW10-45Ligh,sans-serif"
        fontSize:"12px"
        color:"#162D3D"
        lineHeight:"14px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t13:
        fontFamily:"HelveticaNeueW01-45Ligh,HelveticaNeueW02-45Ligh,HelveticaNeueW10-45Ligh,sans-serif"
        fontSize:"30px"
        color:"#162D3D"
        lineHeight:"36px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t14:
        fontFamily:"HelveticaNeueW01-45Ligh,HelveticaNeueW02-45Ligh,HelveticaNeueW10-45Ligh,sans-serif"
        fontSize:"12px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t15:
        fontFamily:"HelveticaNeueW01-45Ligh,HelveticaNeueW02-45Ligh,HelveticaNeueW10-45Ligh,sans-serif"
        fontSize:"12px"
        color:"#162D3D"
        lineHeight:"18px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t16:
        fontFamily:"HelveticaNeueW01-55Roman,HelveticaNeueW02-55Roman,HelveticaNeueW10-55Roman,sans-serif"
        fontSize:"26px"
        color:"#162D3D"
        lineHeight:"36px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t17:
        fontFamily:"HelveticaNeueW01-55Roman,HelveticaNeueW02-55Roman,HelveticaNeueW10-55Roman,sans-serif"
        fontSize:"13px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t18:
        fontFamily:"HelveticaNeueW01-55Roman,HelveticaNeueW02-55Roman,HelveticaNeueW10-55Roman,sans-serif"
        fontSize:"10px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t19:
        fontFamily:"HelveticaNeueW01-65Romann,HelveticaNeueW02-65Romann,HelveticaNeueW10-65Romann,sans-serif"
        fontSize:"18px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t20:
        fontFamily:"HelveticaNeueW01-65Romann,HelveticaNeueW02-65Romann,HelveticaNeueW10-65Romann,sans-serif"
        fontSize:"16px"
        color:"#162D3D"
        lineHeight:"24px"
        textTransform: "none"
        textRendering: "geometricPrecision"
    t21:
        fontFamily:"HelveticaNeueW01-55Roman,HelveticaNeueW02-55Roman,HelveticaNeueW10-55Roman,sans-serif"
        fontSize:"13px"
        color:"#162D3D"
        lineHeight:"18px"
        textTransform: "none"
        textRendering: "geometricPrecision"